### PR TITLE
Added Microsoft Authentication Library (MSAL) AuthenticationService

### PR DESCRIPTION
**Pull request by tycrek**
# Summary

This PR improves [`MsaAuthenticationService`](https://github.com/GeyserMC/MCAuthLib/blob/master/src/main/java/com/github/steveice10/mc/auth/service/MsaAuthenticationService.java) by utilizing the [Microsoft Authentication Library (MSAL) for Java](https://github.com/AzureAD/microsoft-authentication-library-for-java).

### Device code authentication
```java
MsaAuthenticationService auth = new MsaAuthenticationService(AZURE_CLIENT_ID);
auth.setUsername(USERNAME);
auth.setDeviceCodeConsumer((deviceCode) -> {
    if (deviceCode != null) System.out.printf("%s (%s)%n", deviceCode.userCode(), deviceCode.verificationUri());
    else System.out.println("Authenticating using cached tokens...");
});
auth.login();
```

### Username/password authentication
```java
MsaAuthenticationService auth = new MsaAuthenticationService(AZURE_CLIENT_ID);
auth.setUsername(USERNAME);
auth.setPassword(PASSWORD);
auth.login();
```

## SDK version bump

Since [MSAL requires Java 1.8](https://github.com/AzureAD/microsoft-authentication-library-for-java#install), this PR will bump MCAuthLib to Java 1.8: [`tycrek/MCAuthLib/blob/msal-auth-service/pom.xml#L23`](https://github.com/tycrek/MCAuthLib/blob/msal-auth-service/pom.xml#L23)

This should be fine as both MCProtocolLib [`GeyserMC/MCProtocolLib/blob/master/pom.xml#L23`](https://github.com/GeyserMC/MCProtocolLib/blob/master/pom.xml#L23) and PacketLib [`GeyserMC/PacketLib/blob/master/pom.xml#L23`](https://github.com/GeyserMC/PacketLib/blob/master/pom.xml#L23) are using Java 1.8.

## Options

Developers are able to modify MSAL by passing `MSALApplicationOptions` to the `MsaAuthenticationService` constructor. For example:

```java
MsaAuthenticationService auth = new MsaAuthenticationService(
    AZURE_CLIENT_ID, new MSALApplicationOptions.Builder().offlineAccess(true).build());
```

Available options:

- `authority`
- `offlineAccess`
- `scopes`
- `tokenPersistence`

## Caching tokens

This PR adds [`MSALTokenPersistence`](https://github.com/tycrek/MCAuthLib/blob/msal-auth-service/src/main/java/com/github/steveice10/mc/auth/util/MSALTokenPersistence.java), a custom token (de-)serializer for MSAL. This allows developers to easily cache tokens between instances of their programs. This also ensures the user is not required to re-authenticate every time the software is restarted.

Developers are free to add a custom implementation of [`ITokenCacheAccessAspect`](https://www.javadoc.io/doc/com.microsoft.azure/msal4j/0.5.0-preview/com/microsoft/aad/msal4j/ITokenCacheAccessAspect.html), as described on Microsoft's documentation for [Custom token cache serialization in MSAL for Java](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-token-cache-serialization).

### CODE REVIEW

**Comment by tycrek** [comment]
~~Converting to draft to fix that CI failure, built locally.~~ Fixed.

**Comment by tycrek** [comment]
Force-pushes to fix CI failures.

**Comment by Camotoy** [comment]
In my opinion, it's confusing and a bit bloat-y to have two Microsoft implementations. At least on the Geyser end, I'm open to removing the password feature from Microsoft accounts once we implement better options of saving credentials on our end.

**Comment by tycrek** [comment]
What if the existing `MsaAuthenticationService` switched to using MSAL? It would be more reliable in the long run and I could also [add support for username/password](https://github.com/AzureAD/microsoft-authentication-library-for-java/wiki/Acquiring-Tokens-with-username-and-password) fairly easily.

Another benefit is that the MSAL Device Code Flow is mostly handled by the library, making it much easier for developers to implement (can confirm from my own testing). With `MsaAuth`, developers manually need to implement the loop/wait for the Device Code Flow to succeed in the browser. MSAL also handles refresh tokens automatically, saving that step from the developer as well (saving the refresh token to some form of cache).

Not really relevant but I was curious in the JitPack jar sizes:

- GesyerMC 1.4: `46,977 bytes`
- This PR with MSAL: `75,843 bytes`

**Comment by rtm516** [comment]
If you could implement username and password authentication in this PR I'm happy to completely replace the old `MsaAuthenticationService`. The improvements meaning the developers don't need to handle the waiting for the code would be amazing, but if possible still allow that in case people need that feature.

**Comment by tycrek** [comment]
Yep, definitely can do that. Since it is a different implementation of `AuthenticationService` that needs to be used differently in code, I'll drop `Msa` in favour of `MSAL` for now, unless you feel that this should be done differently.

**Comment by Camotoy** [comment]
I would keep the same class names but bump MCAuthLib's version.

**Comment by tycrek** [comment]
Fixed username/password implementation and replaced Device Code with MSAL 👍

**Review by rtm516 — APPROVED** [review]
Code looks ok, I suggest we test and make the changes to Geyser to make sure it all works.

**Comment by tycrek** [comment]
@rtm516 If you pass `null` to `persistence()` on `MSALApplicationOptions.Builder` then it will use in-memory caching. I've got nothing else to add so PR is ready to go when you are

**Review by rtm516 — APPROVED** [review]

**Pull request closed without merging**
